  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: eylulkubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eylulkubernetes
    spec:
      containers:
      - image: gcr.io/kuberneteseylul/github.com/eylulyurdakul/kubernetesworkshop21:cf11a54d224e3b12e5be6a6ef54047c2850c5ccf
        imagePullPolicy: IfNotPresent
        name: eylulkubernetes
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: eylulkubernetes
  name: eylulkubernetes
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30369
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: eylulkubernetes
  sessionAffinity: None
  type: LoadBalancer
