  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: eylulkubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eylulkubernetes
    spec:
      containers:
      - image: gcr.io/kuberneteseylul/github.com/eylulyurdakul/kubernetesworkshop21:cf11a54d224e3b12e5be6a6ef54047c2850c5ccf
        imagePullPolicy: IfNotPresent
        name: eylulkubernetes
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-03-21T15:03:49Z
    lastUpdateTime: 2019-03-21T15:03:49Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-03-21T15:03:13Z
    lastUpdateTime: 2019-03-21T15:03:49Z
    message: ReplicaSet "eylulkubernetes-686c6b885b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
